services:
  db:
    image: postgres:latest
    container_name: vtuber-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    container_name: vtuber-redis
    networks:
      - app-net

  backend:
    image: ghcr.io/gakkyokura/multistreamsearch/backend:latest
    container_name: vtuber-backend
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Docker
    expose:
      - "80"
    networks:
      - app-net

  nginx:
    image: ghcr.io/gakkyokura/multistreamsearch/nginx:latest
    container_name: vtuber-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
